"""add knowledge base tables

Revision ID: 8bb84fbf8fa0
Revises: 4b374b705d24
Create Date: 2024-12-06 16:16:40.398304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb84fbf8fa0'
down_revision = '4b374b705d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
