"""add comments relationship to user

Revision ID: 1e410abba8e3
Revises: 8bb84fbf8fa0
Create Date: 2024-12-06 16:21:19.228116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e410abba8e3'
down_revision = '8bb84fbf8fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
