from enum import Enum

class Gender(str, Enum):
    """Gender options for user profile."""
    MALE = "male"
    FEMALE = "female"
    OTHER = "other"

class MedicalCondition(str, Enum):
    """Medical conditions that may affect health and fitness planning."""
    NONE = "None"
    
    # Cardiovascular
    HYPERTENSION = "Hypertension"
    HEART_DISEASE = "Heart Disease"
    HIGH_CHOLESTEROL = "High Cholesterol"
    
    # Metabolic
    TYPE_1_DIABETES = "Type 1 Diabetes"
    TYPE_2_DIABETES = "Type 2 Diabetes"
    THYROID_DISORDER = "Thyroid Disorder"
    
    # Respiratory
    ASTHMA = "Asthma"
    COPD = "COPD"
    
    # Musculoskeletal
    ARTHRITIS = "Arthritis"
    OSTEOPOROSIS = "Osteoporosis"
    FIBROMYALGIA = "Fibromyalgia"
    
    # Digestive
    CELIAC_DISEASE = "Celiac Disease"
    IBS = "Irritable Bowel Syndrome"
    CROHNS_DISEASE = "Crohn's Disease"
    
    # Mental Health
    ANXIETY = "Anxiety"
    DEPRESSION = "Depression"
    EATING_DISORDER = "Eating Disorder"
    
    # Other
    OTHER = "Other"

class CommonMedication(str, Enum):
    """Common medications that may affect health and fitness planning."""
    NONE = "None"
    BETA_BLOCKERS = "Beta Blockers"
    ACE_INHIBITORS = "ACE Inhibitors"
    INSULIN = "Insulin"
    METFORMIN = "Metformin"
    STATINS = "Statins"
    BLOOD_THINNERS = "Blood Thinners"
    NSAIDS = "NSAIDs"
    CORTICOSTEROIDS = "Corticosteroids"
    ANTIDEPRESSANTS = "Antidepressants"
    ANTI_ANXIETY = "Anti-anxiety Medication"
    THYROID_MEDICATION = "Thyroid Medication"
    BIRTH_CONTROL = "Birth Control"
    INHALERS = "Inhalers"
    ANTIHISTAMINES = "Antihistamines"
    OTHER = "Other"

class CommonAllergy(str, Enum):
    """Common allergies that may affect health and fitness planning."""
    NONE = "None"
    PEANUTS = "Peanuts"
    TREE_NUTS = "Tree Nuts"
    SHELLFISH = "Shellfish"
    FISH = "Fish"
    EGGS = "Eggs"
    MILK = "Milk/Dairy"
    SOY = "Soy"
    WHEAT = "Wheat"
    POLLEN = "Pollen"
    DUST = "Dust"
    MOLD = "Mold"
    PET_DANDER = "Pet Dander"
    PENICILLIN = "Penicillin"
    SULFA_DRUGS = "Sulfa Drugs"
    NSAIDS = "NSAIDs"
    LATEX = "Latex"
    OTHER = "Other"

class PastInjury(str, Enum):
    """Past injuries that may affect exercise planning."""
    NONE = "None"
    CONCUSSION = "Concussion"
    WHIPLASH = "Whiplash"
    NECK_STRAIN = "Neck Strain"
    SHOULDER_INJURY = "Shoulder Injury"
    ROTATOR_CUFF = "Rotator Cuff Injury"
    TENNIS_ELBOW = "Tennis Elbow"
    WRIST_SPRAIN = "Wrist Sprain"
    LOWER_BACK_PAIN = "Lower Back Pain"
    HERNIATED_DISC = "Herniated Disc"
    SCIATICA = "Sciatica"
    HIP_INJURY = "Hip Injury"
    KNEE_INJURY = "Knee Injury"
    ACL_TEAR = "ACL Tear"
    MENISCUS_TEAR = "Meniscus Tear"
    ANKLE_SPRAIN = "Ankle Sprain"
    PLANTAR_FASCIITIS = "Plantar Fasciitis"
    FRACTURE = "Bone Fracture"
    STRESS_FRACTURE = "Stress Fracture"
    MUSCLE_STRAIN = "Muscle Strain"
    LIGAMENT_TEAR = "Ligament Tear"
    TENDONITIS = "Tendonitis"
    OTHER = "Other"

class TimePreference(str, Enum):
    """When do you prefer to exercise?"""
    EARLY_MORNING = "EARLY_MORNING"
    MORNING = "MORNING"
    MIDDAY = "MIDDAY"
    AFTERNOON = "AFTERNOON"
    EVENING = "EVENING"
    LATE_EVENING = "LATE_EVENING"
    FLEXIBLE = "FLEXIBLE"

class ExerciseType(str, Enum):
    """What types of exercise do you prefer?"""
    HIIT = "High-Intensity Interval Training (HIIT)"
    STEADY_CARDIO = "Steady State Cardio"
    ENDURANCE = "Endurance Training"
    POWERLIFTING = "Powerlifting"
    BODYBUILDING = "Bodybuilding"
    STRENGTH_TRAINING = "General Strength Training"
    CROSSFIT = "CrossFit"
    CALISTHENICS = "Calisthenics/Bodyweight"
    YOGA = "Yoga"
    PILATES = "Pilates"
    TAI_CHI = "Tai Chi"
    TEAM_SPORTS = "Team Sports"
    RACKET_SPORTS = "Racket Sports"
    COMBAT_SPORTS = "Combat Sports/Martial Arts"
    SWIMMING = "Swimming"
    CYCLING = "Cycling"
    FUNCTIONAL = "Functional Training"
    REHABILITATION = "Rehabilitation/Physical Therapy"
    LOW_IMPACT = "Low Impact Training"
    OTHER = "Other"

class PreferredSport(str, Enum):
    """What sports do you enjoy?"""
    BASKETBALL = "Basketball"
    FOOTBALL = "Football"
    SOCCER = "Soccer"
    VOLLEYBALL = "Volleyball"
    BASEBALL = "Baseball/Softball"
    HOCKEY = "Hockey"
    TENNIS = "Tennis"
    BADMINTON = "Badminton"
    SQUASH = "Squash"
    TABLE_TENNIS = "Table Tennis"
    BOXING = "Boxing"
    MMA = "Mixed Martial Arts"
    KARATE = "Karate"
    JUDO = "Judo"
    JIU_JITSU = "Brazilian Jiu-Jitsu"
    SWIMMING = "Swimming"
    CYCLING = "Cycling"
    RUNNING = "Running/Track"
    GYMNASTICS = "Gymnastics"
    CLIMBING = "Rock Climbing"
    HIKING = "Hiking"
    SKIING = "Skiing/Snowboarding"
    SURFING = "Surfing"
    SKATEBOARDING = "Skateboarding"
    OTHER = "Other"

class FitnessGoal(str, Enum):
    """Primary fitness and health goals."""
    WEIGHT_LOSS = "WEIGHT_LOSS"
    WEIGHT_MAINTENANCE = "WEIGHT_MAINTENANCE"
    MUSCLE_GAIN = "MUSCLE_GAIN"
    GENERAL_HEALTH = "GENERAL_HEALTH"
    ATHLETIC_PERFORMANCE = "ATHLETIC_PERFORMANCE"
    REHABILITATION = "REHABILITATION"
    STRESS_MANAGEMENT = "STRESS_MANAGEMENT"

class ExerciseIntensity(str, Enum):
    """Intensity of exercise."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
